import type { Metadata } from "next";
import { Sora } from "next/font/google";

import "./globals.css";
import { RoleProvider } from "@/context/RoleContext";

const sora = Sora({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-sora",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Backlyst | Scale Your Backlinks Without The Hassle",
  description: "Generated by S",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={sora.variable}>
        <RoleProvider>{children}</RoleProvider>
      </body>
    </html>
  );
}
