import DashboardLayout from "@/components/layout/DashboardLayout";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Backlyst | Scale Your Backings Without The Hassle",
  description: "Generated by SD",
};

export default function DashboardLayoutPage({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main>
      <DashboardLayout>{children}</DashboardLayout>
    </main>
  );
}
