name: Continous Integration and Deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test-build:
    name: Test and Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install make 
        run: sudo apt-get install make
      - name: Docker hub login
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Create fake .env.production file with empty content
        run: touch .env.production
      - name: Image build and push
        run: make prod-push

  deploy:
    name: Deploy to VPS
    runs-on: ubuntu-latest
    needs: test-build
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Copy Build Files
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_PASSWORD }}
          source: "Makefile,docker-compose.yaml"
          target: "~/frontend"
      - name: Deploy
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_PASSWORD }}
          script: make deploy
